routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/product/{id}',[
    'uses' => 'FrontEndController@singleProduct',
    'as' => 'product.single'
]);

Route::post('/cart/add/{id}',[
    'uses' => 'ShoppingController@add_to_cart',
    'as' => 'cart.add'
]);
Route::get('/cart', [
    'uses' => 'ShoppingController@cart',
    'as' => 'cart'
]);

Route::get('/cart/delete/{id}',[
    'uses' => 'ShoppingController@cart_delete',
    'as' => 'cart.delete'
]);

Route::get('/cart/incr/{id}/{qty}',[
    'uses' => 'ShoppingController@incr',
    'as' => 'cart.incr'
]);
Route::get('/cart/decr/{id}/{qty}',[
    'uses' => 'ShoppingController@decr',
    'as' => 'cart.decr'
]);
Route::get('/cart/rapid/add/{id}',[
    'uses' => 'ShoppingController@rapid_add',
    'as' => 'cart.rapid.add'
]);
Route::get('/cart/checkout',[
    'uses' => 'CheckoutController@index',
    'as' => 'cart.checkout'
]);

Route::post('/cart/checkout',[
    'uses' => 'CheckoutController@pay',
    'as' => 'cart.checkout'
]);

Route::resource('products', 'ProductsController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'image',
        'price',
        'description',
    ];
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;
use Session;
use App\Product;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('products.index',['products' => Product::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'description' => 'required',
            'price' => 'required',
            'image' => 'required|image',
        ]);

        $imagepath = '/uploads/products/';
        $product = new Product;

        $product_image = $request->image;
        $product_image_new_name = time().$product_image->getClientOriginalName();
        $product_image->move(public_path($imagepath),$product_image_new_name);

        $product->name = $request->name;
        $product->price = $request->price;
        $product->image = $imagepath.$product_image_new_name;
        $product->description = $request->description;
        $product->save();

        Session::flash('success','Product created');
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('products.edit',['product' => Product::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required',
            'description' => 'required',
            'price' => 'required',
            'image' => 'required|image',
        ]);

        $product = Product::find($id);
        $imagepath = '/uploads/products/';
        if ($request->hasFile('image')){
            $product_image = $request->image;
            $product_image_new_name = time().$product_image->getClientOriginalName();
            if (file_exists(public_path().$product->image)){
                unlink(public_path().$product->image);
            }
            $product_image->move(public_path($imagepath),$product_image_new_name);

            $product->image = $imagepath . $product_image_new_name;
            $product->save();
        }

        $product->name = $request->name;
        $product->price = $request->price;
        $product->description = $request->description;
        $product->save();

        Session::flash('success','Product updated');

        return redirect() ->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        if (file_exists(public_path().$product->image)){
            unlink(public_path().$product->image);
        }
        $product->delete();
        Session::flash('success','Product deleted');
        return redirect()->back();
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">
        <div class="panel-heading">Create a New Product</div>

        <div class="panel-body">
            <form action="{{route('products.store')}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" class="form-control" value="{{old('name')}}">
                </div>
                <div class="form-group">
                    <label for="price">Price</label>
                    <input type="number" name="price" class="form-control" value="{{old('price')}}">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" name="image" class="form-control">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" rows="10" cols="30" id="description" class="form-control">{{old('description')}}</textarea>
                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">
                            Create product
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">
        <div class="panel-heading">Create a New Product</div>

        <div class="panel-body">
            <form action="{{route('products.update',['id'=>$product->id])}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                {{method_field('PUT')}}
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" class="form-control" value="{{$product->name}}">
                </div>
                <div class="form-group">
                    <label for="price">Price</label>
                    <input type="number" name="price" class="form-control" value="{{$product->price}}">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" name="image" class="form-control">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" rows="10" cols="30" id="description" class="form-control">{{$product->description}}</textarea>
                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">
                            Update product
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="panel panel-default">
        <div class="panel-heading">Products</div>

        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Edit
                    </th>
                    <th>
                        Delete
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $product)
                    <tr>
                        <td>{{$product->name}}</td>
                        <td>{{$product->price}}</td>
                        <td>
                            <a href="{{route('products.edit',['id' => $product->id])}}"
                               class="btn btn-xs btn-info">Edit</a></td>
                        <td>
                            <form action="{{route('products.destroy',['id'=>$product->id])}}" method="post">
                                {{csrf_field()}}
                                {{method_field('DELETE')}}
                                <button class="btn btn-xs btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection